print("Hello World!")
print("Hello WSE!", end="->")
print("Hello Students!")
print("\tGood\nNight!")
print("H","e","l","l","o")
print("H","e","l","l","o",sep="")
print("H","e","l","l","o",sep="*")
print("H"+"e"+"l"+"l"+"o",sep="*")
print("Fun"*6)