numbers = [12, 67, 3, 87, 55, 87, 87]
print(numbers)
print(numbers[1])
print(numbers[-1])
numbers[0] = -21
print(numbers)
numbers.append(100)
print(numbers)
numbers.insert(2, 99)
print(numbers)
numbers.pop()
print(numbers)
numbers.pop(1)
print(numbers)
numbers.remove(87)
print(numbers)
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)